FROM node:8.12.0 as Base

# Set DOCKER_BUILD so that jest will run all the tests (see scripts/test.js)
ENV DOCKER_BUILD yes

ARG DMCA_CONTENT_ENDPOINT
ARG DMCA_USER_ENDPOINT
ARG LIQUID_TOKEN
ENV REACT_APP_DMCA_CONTENT_ENDPOINT $DMCA_CONTENT_ENDPOINT
ENV REACT_APP_DMCA_USER_ENDPOINT $DMCA_USER_ENDPOINT
ENV REACT_APP_LIQUID_TOKEN $LIQUID_TOKEN

ARG APP_API_URL
ARG APP_API_ADDRESS_PREFIX
ARG APP_API_CHAIN_ID
ENV REACT_APP_API_URL $APP_API_URL
ENV REACT_APP_API_ADDRESS_PREFIX $APP_API_ADDRESS_PREFIX
ENV REACT_APP_API_CHAIN_ID $APP_API_CHAIN_ID


ARG AVATAR_PROXY
ARG AVATAR_UPLOAD_ENDPOINT
ARG AVATAR_UPLOAD_PREFIX
ARG VIDEO_THUMBNAIL_URL_PREFIX
ARG VIDEO_UPLOAD_ENDPOINT
ARG IMAGE_UPLOAD_ENDPOINT
ARG VIDEO_HISTORY_ENDPOINT
ARG VIDEO_UPLOAD_POSTED_ENDPOINT
ENV REACT_APP_AVATAR_PROXY $AVATAR_PROXY
ENV REACT_APP_AVATAR_UPLOAD_ENDPOINT $AVATAR_UPLOAD_ENDPOINT
ENV REACT_APP_AVATAR_UPLOAD_PREFIX $AVATAR_UPLOAD_PREFIX
ENV REACT_APP_VIDEO_THUMBNAIL_URL_PREFIX $VIDEO_THUMBNAIL_URL_PREFIX
ENV REACT_APP_VIDEO_UPLOAD_ENDPOINT $VIDEO_UPLOAD_ENDPOINT
ENV REACT_APP_IMAGE_UPLOAD_ENDPOINT $IMAGE_UPLOAD_ENDPOINT
ENV REACT_APP_VIDEO_HISTORY_ENDPOINT $VIDEO_HISTORY_ENDPOINT
ENV REACT_APP_VIDEO_UPLOAD_POSTED_ENDPOINT $VIDEO_UPLOAD_POSTED_ENDPOINT

WORKDIR /var/app
RUN mkdir -p /var/app
COPY . /var/app
RUN env
ENV NODE_ENV development
RUN npm upgrade yarn
RUN yarn cache clean
RUN yarn install --network-concurrency=1
ENV NODE_ENV production
RUN yarn run build

#RUN mkdir tmp && \
#    npm test && npm run build

FROM Base as Development

ENV PORT 8080
ENV NODE_ENV production

EXPOSE 8080

# uncomment the lines below to run it in development mode
# ENV NODE_ENV development
CMD [ "yarn", "run", "start" ]

FROM nginx:alpine as Production

COPY --from=Base /var/app/build /usr/share/nginx/html
COPY --from=Base /var/app/yarn.lock /root/yarn.lock
